stages:
  - deploy

deploy_to_vps:
  stage: deploy
  tags:
    # Тэг раннера
    - shell
  script:
    # SSH доступ
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

    # Очистка рабочего репозитория
    - ssh root@$SERVER_HOST << 'EOF'
        rm -rf /opt/*
      EOF

    # Копируем файлы на сервер
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@$SERVER_HOST:/opt/django_app/

    # Деплой докер контейнера
    - ssh root@$SERVER_HOST << 'EOF'
        sudo mkdir -p /opt/django_app_static/
        sudo mkdir -p /opt/django_app_data/
        cd /opt/django_app/
        docker-compose down
        docker-compose pull
        docker-compose up -d --build
      EOF

    # Запуск Nginx
    - ssh root@$SERVER_HOST << 'EOF'
        sudo apt install -y nginx
        sudo rm /etc/nginx/sites-enabled/default
        rm /etc/nginx/sites-available/django_app.nginx || true
        rm /etc/nginx/sites-enabled/django_app.nginx || true
        sudo ln -s /opt/django_app/conf/django_app.nginx /etc/nginx/sites-available/
        sudo ln -s /etc/nginx/sites-available/django_app.nginx /etc/nginx/sites-enabled/
        cat /etc/nginx/sites-enabled/django_app.nginx
        sudo nginx -t
        sudo systemctl restart nginx
      EOF

  only:
    # Условия запуска пайплайна
    - main

  rules:
    - if: $CI_COMMIT_BRANCH == 'staging' && $CI_COMMIT_REF_PROTECTED == 'true'
