name: Deploy to VPS

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Клонируем репозиторий
    - name: Checkout code
      uses: actions/checkout@v3

    # Устанавливаем SSH доступ
    - name: Setup SSH
      if: ${{ success() }}
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Очистка рабочего репозитория
    - name: Clear working repo
      if: ${{ success() }}
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} << 'EOF'
          rm -rf /opt/*
        EOF

    # Копируем файлы на сервер
    - name: Copy files to server
      if: ${{ success() }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@${{ secrets.SERVER_HOST }}:/opt/django_app/

    # Выполняем команды на сервере для деплоя
    - name: Deploy Docker container
      if: ${{ success() }}
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} << 'EOF'
          sudo mkdir -p /opt/django_app_static/
          sudo mkdir -p /opt/django_app_data/
          cd /opt/django_app/
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
        EOF

    # Запуск Nginx
    - name: Configure Nginx
      if: ${{ success() }}
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} << 'EOF'
          sudo apt install -y nginx
          sudo rm /etc/nginx/sites-enabled/default
          rm /etc/nginx/sites-available/django_app.nginx
          rm /etc/nginx/sites-enabled/django_app.nginx
          sudo ln -s /opt/django_app/conf/django_app.nginx /etc/nginx/sites-available/
          sudo ln -s /etc/nginx/sites-available/django_app.nginx /etc/nginx/sites-enabled/
          cat /etc/nginx/sites-enabled/django_app.nginx
          sudo nginx -t
          sudo systemctl restart nginx
        EOF
